version: "3.3"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  jumpget:
    image: "lsgrep/jumpget"
    container_name: "jumpget"
    ports:
      - 127.0.0.1:4100:4100
    environment:
      - JUPMGET_PUBLIC_PORT=3100
      - JUMPGET_LOCAL_PORT=4100
      - JUMPGET_PUBLIC_URL=https://jumpget.example.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jumpget.rule=Host(`jumpget.example.com`)"
      - "traefik.http.routers.jumpget.tls.certresolver=myresolver"
      - "traefik.http.routers.jumpget.entrypoints=websecure"
      - "traefik.http.routers.jumpget.service=jumpget"
      - "traefik.http.services.jumpget.loadbalancer.server.port=3100"
