version: 2
jobs:
  test-build-job:
    docker:
      - image: circleci/golang
    environment:
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/go/src/github.com/lsgrep/jumpget
    steps:
      - checkout
      - run:
          name: Bash fix
          command: |
            echo 'export PATH=$PATH:$GOPATH/bin' >> $BASH_ENV
      - run:
          name: Test & Lint
          command: |
            go get
            go test $(go list ./... | grep -v /vendor/)
      - run:
          name: Compile & Release
          command: |
            export BUILD_DATE=$(TZ=UTC date -u '+%Y-%m-%dT%H:%M:%SZ')
            export GIT_HASH=$(git rev-parse HEAD)
            export PROJECT_URL=github.com/$CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}
            export CURRENT_VERSION=v0.1.$CIRCLE_BUILD_NUM
            go get github.com/mitchellh/gox
            go get -u github.com/tcnksm/ghr
            CGO_ENABLED=0 gox -arch="amd64" -ldflags "-X $PROJECT_URL/main.version=$CURRENT_VERSION -X $PROJECT_URL/main.buildDate=$BUILD_DATE -X $PROJECT_URL/main.gitHash=$GIT_HASH" -output "dist/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}"
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 $CURRENT_VERSION dist/ || true


workflows:
  version: 2
  build-deploy:
    jobs:
      - test-build-job:
          filters:
            branches:
              only: master
